### PR TITLE
Update waveshape label when changed by control

### PR DESCRIPTION
**Pull request by jpcima**
Hi. Usually the waveshape text would not update after it is has been changed by moving the slider.
This commit will solve the problem.

### CODE REVIEW

**Comment by nicoroulet** [comment]
Thanks! Would you care to tell me a bit about your experience with this synth? (as you might have noticed, this is a fairly old project so I'm glad someone actually tried it :) )

**Comment by jpcima** [comment]
Hi @nicoroulet.

>Thanks! Would you care to tell me a bit about your experience with this synth?

Oh absolutely. I had a positive experience with the synth, and I was surprised at the pleasing sounds it 
was able to output given it's design implicity (speaking as someone who has owned Moog); I have also a few elements to criticize about it.

It was actually members on the french team who enjoyed the software who brought my attention to it.
Me, I'm essentially a developer, not musician. There was a discussion at this link; the goal is to provide the software in the OS distribution LibraZiK.
https://librazik.tuxfamily.org/flyspray/index.php?do=details&task_id=735 :fr:

I would make this criticism:
- no oscillator band-limiting; the aliasing noise gets very high in the high notes, making this note range is not very practical at all.
- no presets. I had a thought on this: the modern Moogs which are digital-controlled have some factory banks downloadable, it would be interesting to research if their import can be made.
- it would be nice if it can evolve with a modern set of features modern Moogs have also provided. (things coming to mind are duophony/polyphony, phatty overdrive, oscillator sync, etc)

**Comment by nicoroulet** [comment]
Great! Thank you for sharing. I'm glad you had a good experience with it, and that there are actually several people that tried it.
Oscillator band-limiting is something that we were not aware of at the time but is a quite important feature.
I think I recall being able to create and load presets through hosts like Ardour. This was a university project, so implementing custom presets was never in the scope of the project but I agree it would be a nice thing to have.
We only ever had access to old-school moogs, so polyphony is not something we ever considered. LFOs, however, was something we really wanted to add at the time.
Let's keep in touch if you really intend to include it in LibraZiK! :)

**Comment by trebmuh** [comment]
Hi, I'm the LibraZiK's packager. Right now, the software is in the testing phase.

**Comment by trebmuh** [comment]
@nicoroulet : just to let you know, the software works as expected (both in 32 bits and 64 bits) and is going to hit the users repo in a few days from now probably.

**Comment by nicoroulet** [comment]
Fantastic, thanks for the heads-up!

**Pull request merged**
